version: 0.2

phases:
  install:
    commands:
      - echo Installing Node 12...
  pre_build:
    commands:
      - echo Installing dependencies...
  build:
    commands:
      - echo Testing...
  post_build:
    commands:
      - echo Post-Build..
artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: dist
